// ! (!) - Important comments valueable information
// & (?) - Heading 
// * (*) - Sub heading
// ~ (~) - Bullets 
// ? (?) - Dots
// ^ (^) - Example/Explanation 

#include<iostream>
using namespace std;
int main()
{
    cout << "Exception handling" << endl;
    // ^ It is an unexpected problem during the execution of a program
    // * Try - A block of code which may cause an exception is typically placed inside the try block
    /*
    * Catch - This block catches the exception thrown from the try block.
    * Code to handle the exception is written inside this catch block.
     */ 
    // * A program throws an exception when a problem shows up. This is done using a throw keyword

    return 0;
}